networks:
  yugabyte_net:
    name: yugabyte_net

volumes:
  yugabytedb-data:

x-logging:
  &default-logging
  options:
    max-size: '20m'
    max-file: '3'
  driver: json-file

services:
  yugabytedb:
    container_name: yugabytedb
    image: yugabytedb/yugabyte:2024.1.0.0-b129
    init: true
    environment:
      - TINI_SUBREAPER=true
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en # Or just en_US.UTF-8
      - LC_ALL=en_US.UTF-8
#    logging: *default-logging
    ports:
      - "7001:7000"
      - "9000:9000"
      - "15433:15433"
      - "5433:5433"
      - "9042:9042"
    command: [
      "/home/yugabyte/bin/yugabyted",
      "start",
      "--base_dir=/home/yugabyte/yb_data",
      "--background=false"
    ]
    volumes:
      - yugabytedb-data:/home/yugabyte/yb_data
#      - "../data/yugabytedb/single-node:/root/var/data" #using a wrong path make the container at least to start
#     - "../data/yugabytedb/single-node:/home/yugabyte/yb_data"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/home/yugabyte/postgres/bin/pg_isready -h yugabytedb -p 5433 -U yugabyte || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - yugabyte_net

